//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViviScapeIceCream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flavor
    {
        public int intFlavorID { get; set; }
        public string strFlavor { get; set; }
        public Nullable<decimal> decStock { get; set; }
        public Nullable<decimal> decCost { get; set; }
        public Nullable<decimal> decPrice { get; set; }
        public Nullable<bool> bitDiscontinued { get; set; }
        public Nullable<bool> bitFeatured { get; set; }
    }
}
