//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViviScapeIceCream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int intSaleID { get; set; }
        public Nullable<int> intFlavor { get; set; }
        public Nullable<int> intQty { get; set; }
        public Nullable<decimal> curCost { get; set; }
        public Nullable<decimal> curSalePrice { get; set; }
        public Nullable<System.DateTime> dtmDateSold { get; set; }
    }
}
